<?php
/**
 * AgriSync — AI Match Results & Offer Acceptor (TASK-045 / TASK-011)
 * Displays algorithmic pairings generated by the Autonomous AI Broker Agent.
 */

require_once __DIR__ . '/../config/session.php';
require_once __DIR__ . '/../config/constants.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../auth/auth_check.php';
require_once __DIR__ . '/../includes/functions.php';

// Strict Business Role Access Control
requireRole('business');

$page_title = 'AI Match Deals';
$user_id = (int) ($_SESSION['user_id'] ?? 0);
$filter_order_id = isset($_GET['order_id']) ? (int)$_GET['order_id'] : 0;

$matches = [];
$error_msg = '';

try {
    $db = getDbConnection();

    $sql = "
        SELECT 
            m.id as match_id, m.order_id, m.farmer_id, m.matched_price, m.confidence_score, 
            m.agent_reasoning, m.status as match_status, m.created_at as matched_date,
            o.crop_type, o.quantity_kg, o.max_price as requested_max_price, o.delivery_date,
            u.name as farmer_name, u.district as farmer_district, u.phone as farmer_phone,
            p.status as payment_status, p.payhere_payment_id
        FROM order_matches m
        JOIN order_requests o ON m.order_id = o.id
        JOIN users u ON m.farmer_id = u.id
        LEFT JOIN payments p ON m.id = p.order_match_id
        WHERE m.business_id = :business_id
    ";
    $params = [':business_id' => $user_id];

    if ($filter_order_id > 0) {
        $sql .= " AND m.order_id = :order_id";
        $params[':order_id'] = $filter_order_id;
    }

    $sql .= " ORDER BY m.id DESC";

    $stmt = $db->prepare($sql);
    $stmt->execute($params);
    $matches = $stmt->fetchAll(PDO::FETCH_ASSOC);

} catch (Throwable $e) {
    error_log("Matches Fetch Error: " . $e->getMessage());
    $error_msg = "Unable to retrieve AI matchmaking records.";
}

require_once __DIR__ . '/../includes/header.php';
require_once __DIR__ . '/../includes/navbar.php';
?>

<div class="d-flex" style="min-height: 100vh;">
    <!-- Role-based Sidebar Navigation -->
    <?php require_once __DIR__ . '/../includes/sidebar.php'; ?>

    <!-- Main Content Area -->
    <div class="flex-grow-1 bg-light p-4 overflow-auto">
        <div class="container-fluid max-w-7xl">
            
            <!-- Header -->
            <div class="d-flex flex-wrap align-items-center justify-content-between mb-4 pb-2 border-bottom">
                <div>
                    <h1 class="h3 fw-bold text-dark mb-1">
                        <i class="bi bi-robot text-success me-2"></i>Autonomous AI Broker Deals
                    </h1>
                    <p class="text-muted small mb-0">
                        Intelligent produce pairings generated from verified farmer inventories across Sri Lanka.
                    </p>
                </div>
                <div class="d-flex gap-2 mt-3 mt-md-0">
                    <a href="place_order.php" class="btn btn-primary rounded-3 shadow-sm">
                        <i class="bi bi-plus-circle-fill me-1"></i> New Order Request
                    </a>
                </div>
            </div>

            <?php if (!empty($error_msg)): ?>
                <div class="alert alert-danger rounded-3"><?= htmlspecialchars($error_msg, ENT_QUOTES, 'UTF-8') ?></div>
            <?php endif; ?>

            <?php if (empty($matches)): ?>
                <div class="card border-0 shadow-sm rounded-4 p-5 text-center bg-white">
                    <div class="py-4">
                        <i class="bi bi-stars text-warning fs-1 d-block mb-3"></i>
                        <h4 class="fw-bold text-dark">No Active AI Matches Yet</h4>
                        <p class="text-muted small mx-auto" style="max-width: 480px;">
                            When you submit commercial procurement requests, our autonomous Gemini AI broker instantly scans verified farm yields to negotiate high-confidence pairings.
                        </p>
                        <a href="place_order.php" class="btn btn-primary rounded-3 mt-2">Place an Order Request</a>
                    </div>
                </div>
            <?php else: ?>
                <div class="row g-4">
                    <?php foreach ($matches as $deal): ?>
                        <?php
                            $st = $deal['match_status'];
                            $badge = 'bg-secondary-subtle text-secondary';
                            if ($st === 'proposed') $badge = 'bg-warning-subtle text-warning border border-warning';
                            if ($st === 'accepted') $badge = 'bg-success-subtle text-success border border-success';
                            if ($st === 'completed') $badge = 'bg-primary-subtle text-primary border border-primary';
                            
                            $score = (int)$deal['confidence_score'];
                            $total_deal_val = (float)$deal['quantity_kg'] * (float)$deal['matched_price'];
                        ?>
                        <div class="col-12 col-xl-6">
                            <div class="card border-0 shadow-sm rounded-4 bg-white h-100 p-4">
                                
                                <div class="d-flex justify-content-between align-items-start mb-3">
                                    <div>
                                        <span class="badge rounded-pill bg-light text-dark border mb-1">
                                            #MATCH-<?= (int)$deal['match_id'] ?> &bull; Order #<?= (int)$deal['order_id'] ?>
                                        </span>
                                        <h4 class="fw-bold text-dark mb-0"><?= htmlspecialchars($deal['crop_type'], ENT_QUOTES, 'UTF-8') ?></h4>
                                    </div>
                                    <span class="badge rounded-pill <?= $badge ?> px-3 py-2 text-capitalize">
                                        <?= htmlspecialchars($st, ENT_QUOTES, 'UTF-8') ?>
                                    </span>
                                </div>

                                <!-- Key Metrics Grid -->
                                <div class="row g-2 mb-3">
                                    <div class="col-6 col-sm-3">
                                        <div class="p-2 bg-light rounded-3 text-center">
                                            <small class="text-muted extra-small d-block">Volume</small>
                                            <strong class="text-dark"><?= number_format($deal['quantity_kg'], 1) ?> kg</strong>
                                        </div>
                                    </div>
                                    <div class="col-6 col-sm-3">
                                        <div class="p-2 bg-light rounded-3 text-center">
                                            <small class="text-muted extra-small d-block">Matched Price</small>
                                            <strong class="text-success">Rs. <?= number_format($deal['matched_price'], 2) ?></strong>
                                        </div>
                                    </div>
                                    <div class="col-6 col-sm-3">
                                        <div class="p-2 bg-light rounded-3 text-center">
                                            <small class="text-muted extra-small d-block">Total Value</small>
                                            <strong class="text-dark">Rs. <?= number_format($total_deal_val, 2) ?></strong>
                                        </div>
                                    </div>
                                    <div class="col-6 col-sm-3">
                                        <div class="p-2 bg-light rounded-3 text-center">
                                            <small class="text-muted extra-small d-block">AI Score</small>
                                            <strong class="text-primary"><?= $score ?>% Match</strong>
                                        </div>
                                    </div>
                                </div>

                                <!-- Farmer Details -->
                                <div class="p-3 bg-light rounded-3 mb-3 border-start border-success border-4">
                                    <div class="d-flex justify-content-between align-items-center mb-1">
                                        <span class="fw-bold text-dark"><i class="bi bi-person-badge text-success me-1"></i> <?= htmlspecialchars($deal['farmer_name'], ENT_QUOTES, 'UTF-8') ?></span>
                                        <span class="badge bg-white text-muted border"><?= htmlspecialchars($deal['farmer_district'], ENT_QUOTES, 'UTF-8') ?></span>
                                    </div>
                                    <div class="small text-muted">
                                        <i class="bi bi-telephone-fill me-1"></i> Contact: <strong><?= htmlspecialchars($deal['farmer_phone'] ?? 'Verified via Hub', ENT_QUOTES, 'UTF-8') ?></strong>
                                    </div>
                                </div>

                                <!-- Agent Reasoning Box -->
                                <div class="mb-4">
                                    <small class="fw-semibold text-muted d-block mb-1">
                                        <i class="bi bi-magic text-warning me-1"></i> AI Broker Match Rationale:
                                    </small>
                                    <div class="p-3 bg-light rounded-3 border small text-dark fst-italic">
                                        "<?= htmlspecialchars($deal['agent_reasoning'], ENT_QUOTES, 'UTF-8') ?>"
                                    </div>
                                </div>

                                <!-- Action Buttons -->
                                <div class="mt-auto d-flex flex-wrap gap-2 justify-content-between align-items-center border-top pt-3">
                                    <div>
                                        <?php if ($deal['payment_status'] === 'paid'): ?>
                                            <span class="badge bg-success-subtle text-success border border-success px-2 py-1 small">
                                                <i class="bi bi-shield-lock-fill me-1"></i> Escrow Paid
                                            </span>
                                        <?php elseif ($deal['payment_status'] === 'escrow_released'): ?>
                                            <span class="badge bg-primary-subtle text-primary border border-primary px-2 py-1 small">
                                                <i class="bi bi-check-all me-1"></i> Escrow Released
                                            </span>
                                        <?php else: ?>
                                            <span class="badge bg-light text-muted border px-2 py-1 small">
                                                <i class="bi bi-clock me-1"></i> Escrow Pending
                                            </span>
                                        <?php endif; ?>
                                    </div>
                                    <div class="d-flex gap-2">
                                        <?php if ($deal['payment_status'] === 'paid' || $deal['payment_status'] === 'escrow_released'): ?>
                                            <a href="checkout.php?match_id=<?= (int)$deal['match_id'] ?>" class="btn btn-outline-success btn-sm rounded-3 px-3">
                                                <i class="bi bi-receipt me-1"></i> Escrow Receipt
                                            </a>
                                        <?php else: ?>
                                            <a href="checkout.php?match_id=<?= (int)$deal['match_id'] ?>" class="btn btn-success btn-sm rounded-3 px-3 shadow-sm" style="background-color: #2D6A4F; border-color: #2D6A4F;">
                                                <i class="bi bi-credit-card-fill me-1"></i> Pay via PayHere Escrow
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                </div>

                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

        </div>
    </div>
</div>

<script>
function acceptDeal(matchId) {
    if (confirm('Accept this direct farm trade deal and notify the producer?')) {
        alert('Deal accepted! Logistic coordination instructions dispatched to both parties.');
        window.location.reload();
    }
}
</script>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>
